title: "Les Mégères de l'Humus"
default_lang: fr
author:
  name: 'Suzie Idlas & Sabine Rance'
  email: compagnie@lesmegeresdelhumus.fr
metadata:
  description: "La Compagnie Les Mégères de l'Humus est une une compagnie de théâtre éco-queer, féministe et artiviste située à Moussoulens dans l'Aude en Occitanie."