title: "Les Mégères de l'Humus"
default_lang: fr
author:
  name: 'Suzie Idlas & Sabine Rance'
  email: compagnie@lesmegeresdelhumus.fr
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
